# Generated by Django 5.2 on 2025-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_app',
                'managed': False,
            },
        ),
    ]
